### ISSUE TITLE
Textures?

### ISSUE THREAD

**Issue by ehdrew420** [Riqorm/PlayHomeVR#7]
While playing and switching positions sometimes the textures appear to glitch and I get a very realistic looking skin (I assume from the games normal pp effects) but the shoulders look rainbow colored. Only way to fix has been to exit and reenter scene thus far. Any ideas? Does this mean the proper textures in vr are within grasp?  Thanks for all the work modifying eusths code for us!

**Comment by Riqorm** [comment]
I'm not sure what you mean. The skin in VR should look the same as on desktop - if your textures are missing then there seems to be some problem with your installation. Possible because you installed some texture mods or something?

**Comment by ehdrew420** [comment]
Thanks for the response. I did manage to figure out the issue im facing has nothing to do with this mod. Looking forward to the expansion of the obey tool! Keep up the great work.
