### ISSUE TITLE
VR Mode won't launch

### ISSUE THREAD

**Issue by junpieeh** [Riqorm/PlayHomeVR#9]
Can't get VR mode to launch. Steam VR is up and running. Had a similar issue with HS official VR mode, but not with Eusth VR mod for HS.

Using Vive and deleted the VRtrial and ran through IPA again.

**Comment by Riqorm** [comment]
Did it work with the Trail plugin? Also attach or paste the vr.log file (in your game directory).

**Comment by junpieeh** [comment]
Didn't try the trial. Also do not have vr.log file in Playhome directory. No issues with Steam or Oculus store VR but again, did have same issue with HS official VR (but not VR mod).

**Comment by Riqorm** [comment]
Start the PlayHome64bit.exe with the argument "--vr". If nothing else that should create a log file.

**Comment by junpieeh** [comment]
Yes, that worked. Not sure what the problem was. Thanks.
